### ISSUE TITLE
Conversation with Whatsapp

### ISSUE THREAD

**Issue by ftrapnell** [watson-developer-cloud/botkit-middleware#119]
Hi, I came here through [Mitch Mason's article](https://www.ibm.com/blogs/watson/2016/11/new-botkit-integration-makes-deploying-watson-bots-messaging-apps-easy/). 

Where he says that it's possible to make Watson with botkit conversation to talk with Message Apps. But, I didn't find any reference regarding using Whatsapp.  Apparently There's no Whatsapp API available. 

My objective is to read an Whatsapp message and create an incident in an ITSM tool. So I though that it would be nice to have Mr. Watson doing this job. 

Does anyone have seen, or made such kind of integration?

**Comment by Naktibalda** [comment]
Correct question to ask is "How could I integrate botkit with Whatsapp" - and it is better to ask it in the botkit repo: https://github.com/howdyai/botkit/issues

Since there is no such module in npm and no existing issues in botkit repo, it probably falls onto you to implement it.

I've seen this response by Mitch in WDC Slack 2 months ago:
> WhatsApp does not currently allow bots. Thy have a beta program you can apply to  to add a bot, but you have to work with them.

**Comment by germanattanasio** [comment]
closing since it's not related to this repository
