### ISSUE TITLE
Handling Watson downtime

### ISSUE THREAD

**Issue by jganseman** [watson-developer-cloud/botkit-middleware#125]
On the rare occasion that the Watson service is down (as happened on 26 jan'18), it seems that Controller.hears() gets empty or incomplete messages back. It leads to an error: 
> 'Fatal TypeError: Cannot read property 'watsonError' of undefined'

I'm not well-versed in JS, and I'm not sure how to reproduce. Would it make sense to, in the example files, in the hears() function, to add a line 
> if (message && message.watsonData)

?

**Comment by Naktibalda** [comment]
Was it actually down? I only got Protocol Error responses that were valid messages.

**Comment by jganseman** [comment]
I'm not sure tbh. Do Protocol Errors also go into the .watsonError field? Is there a list of the possible watsonErrors anywhere? If so, this issue might just be solved with maybe some extra docs/examples about error handling.

**Comment by Naktibalda** [comment]
> Fatal TypeError: Cannot read property 'watsonError' of undefined

This error couldn't be caused by Friday's issue - either something else is wrong in the code of middleware (unlikely), or it is a programming bug in your code.

`message` object is not reconstructed from Watson response, it is the original Botkit message which arrived from Slack (or whatever network you are using), middleware only adds `watsonData` or `watsonError` property to it.

https://github.com/watson-developer-cloud/botkit-middleware/blob/v1.7.1/lib/middleware/index.js#L118-L125
