### ISSUE TITLE
Message filtering

### ISSUE THREAD

**Issue by ca42rico** [watson-developer-cloud/botkit-middleware#135]
Hi! I would like to filter the incoming messages of some users, in the sense that I would like to answer only certain users (and not others). Where can I check and stop botkit+watson from analyze the messages (so that Assistant does not receive the messages)?
Thanks!

**Comment by pgoldweic** [comment]
I would definitely wrap the Watson middleware (instead of registering it) so my code could include the logic to decide whether to actually send messages to Watson or not.
Take a look at the readme file for Watson middleware, specifically 'Message Filtering', and 'Using interpret function instead of registering middleware'.

**Comment by ca42rico** [comment]
Thank you very much, I solved!
