### ISSUE TITLE
Facebook bot does not reply back

### ISSUE THREAD

**Issue by jerinsj** [watson-developer-cloud/botkit-middleware#99]
![screenshot 1](https://user-images.githubusercontent.com/16564697/30516613-c933f8a6-9b11-11e7-9607-46845e3eec49.png)
![issue](https://user-images.githubusercontent.com/16564697/30516578-263f73f0-9b11-11e7-8527-5f2dd74213a5.PNG)

Can anyone tell me what the fatal type error means and how i can get the facebook bot to reply back. I used localtunnel just to try out the facebook bot, here's how that looks in the visual code terminal....
![localtunnel](https://user-images.githubusercontent.com/16564697/30516599-8ff3222e-9b11-11e7-9751-5b56b455d550.PNG)

**Comment by newbies13** [comment]
I am getting the same error, it looks like they've had this problem before, there is a reference to a #28 which was fixed but seems to have popped up again.

**Comment by Naktibalda** [comment]
Are you checking message.watsonError before using message.watsonData in your code?

**Comment by jerinsj** [comment]
where can i check message.watsonError and message.watsonData and how do you know if that could be a problem?

**Comment by Naktibalda** [comment]
Replace bot.reply line with
```js
 if (message.watsonError.) {
    console.log(message.watsonError);
    bot.reply(message, "I'm sorry, but for technical reasons I can't respond to your message");
  } else {
    bot.reply(message, message.watsonData.output.text.join('\n'));
  }
```

**Comment by jerinsj** [comment]
I am going to try that and let you know, although i don't think that will get the bot to have a conversation.

**Comment by Naktibalda** [comment]
No, but it will help to understand why your bot isn't working.

**Comment by jerinsj** [comment]
Yes my friend I tried that and this is the message that I see...
![issue2](https://user-images.githubusercontent.com/16564697/30766939-8719b21c-9fc6-11e7-9ff7-03f8aacb13a0.PNG)

leading upto this...  I used local tunnel set it to listen on port 5000, received URL for webhook, went on facebook and added the webhook, everything went well but that's the error message I get on the terminal...

**Comment by jerinsj** [comment]
oh wow! the bot responded " I'm sorry but for technical reasons cant respond to your message. 
![msg](https://user-images.githubusercontent.com/16564697/30767087-d571c50c-9fc7-11e7-9e3e-3fb87ab9c93a.PNG)

**Comment by Naktibalda** [comment]
It looks like you get Forbidden response from Watson. Check if you are setting correct username, password and workspace_id.

**Comment by kkarlallan** [comment]
Good Day Guys,

I've had the same initial issue with @jerinsj. And the error logs say "ERCD-NOCONFIG"
![image](https://user-images.githubusercontent.com/17855490/30776151-2b423bee-a0d4-11e7-9028-94a3079a3e53.png)

you can print this by following below:
![image](https://user-images.githubusercontent.com/17855490/30776171-5f1cf17a-a0d4-11e7-9ac3-37aa44594101.png)

Further research suggests that this points to having incorrect username, password, or workspace_id like what @Naktibalda said. BUT, here's the issue with the Botkit I've found:

I've tried adding in the credentials manually and they don't work. as seen here:
![image](https://user-images.githubusercontent.com/17855490/30776188-b7711a54-a0d4-11e7-8557-34eddfb16b4f.png)

I also noticed that in the Application details in Bluemix, the conversation service was binded and a different set of credentials were given, I tried them also and to no success. I've read from a different post that this might be due to the `version_date` sending the wrong POST request format like "https://gateway.watsonplatform.net/conversation/api/v1/workspaces/{workspace_id}/message?version=`ConversationV1.VERSION_DATE_2017_05_26`". 

May I request help? or can someone teach me how to see the POST requests my botkit is sending to the Watson API endpoint?

**Comment by Naktibalda** [comment]
@kkarlallan I see 2 unrelated pieces of code.
The first screenshot is a complete code of a very minimal bot which does nothing.

Second screenshot creates middleware object.
Is there a third file which plugs the first two together?

URL in the error log looks completely wrong too.

My advice is not to use Watson middleware example code as a starting point for your bot. Use botkit starter kit instead and plug Watson middleware to it.

**Comment by kkarlallan** [comment]
Hey @Naktibalda . I fixed my problem and I'm guessing this will fix @jerinsj 's problem too. Thanks for putting a bit of time into this. This was quite embarrassing.

But before that, the first screenshot is the small white one; the logs from Bluemix. I tried to show the JSON response from Watson so you can see in the error in the JSON response "ERCD-NOCONFIG".

The second screenshot is the location where I did the `console.log`. (you can see the "===MESSAGE HERE")

The third screenshot is me manually inputting my conversation credentials instead of using the environment prop. 

And, here's the absurd solution:
In the .env file. Delete the commented "#US-South" on line 2. Voila!
![image](https://user-images.githubusercontent.com/17855490/30777754-c60b1d10-a0f4-11e7-90f2-bfd7fe3db148.png)

This took me 3 days to find out. What a life. *sigh

**Comment by jerinsj** [comment]
Awesome! that was exactly the problem. Thanks. I am so excited to be talking with my bot for the very first time.

**Comment by Naktibalda** [comment]
@kkarlallan sorry for that, I assumed that # comments work like in programming languages and didn't test them.
